/**
 * Master Track Catalogue & Static Manifest Fallback (lib/constants/tracks.ts)
 * 
 * Project: Solitude (Midnight Sad Songs Sanctuary)
 * Runtime: Next.js 15, React 19, TypeScript (Strict Mode)
 * Backend: Supabase Public Storage (HTTP 206 Byte-Range Streaming)
 * Scope: 30 Curated Sad Songs (Complete Metadata, Storage Endpoints & Ambient Loops)
 * 
 * Zero any, zero placeholders, complete production constants.
 */

import { Song, AmbientStemKey } from "@/types/contracts";

export const STORAGE_BASE_URL = "https://obdjrxhjzrlbgkypascy.supabase.co/storage/v1/object/public";

/**
 * Public storage endpoints for independent looping ambient soundscapes.
 * These stems bypass the master Lo-Fi filter directly into AudioContext.destination.
 */
export const AMBIENT_STEMS: Record<AmbientStemKey, string> = {
  rain: `${STORAGE_BASE_URL}/ambient/rain.mp3`,
  thunder: `${STORAGE_BASE_URL}/ambient/thunder.mp3`,
  vinyl: `${STORAGE_BASE_URL}/ambient/vinyl.mp3`,
};

/**
 * Canonical 30-track fallback manifest matching public.songs seed data exactly.
 * Used for instant client hydration and graceful offline playback.
 */
export const FALLBACK_TRACKS: Song[] = [
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
    track_order: 1,
    title: "Raanjhan",
    artist: "Sachet Tandon, Parampara Tandon",
    duration_seconds: 241,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-001.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-001.webp`,
    shayari_quote: "Raanjhan dhoondhan main chali, khud hi se ghum ho gayi...",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "a12b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    track_order: 2,
    title: "Finding Her (Slowed + Reverb)",
    artist: "Kushagra, Vanshika Kashyap, Bharath",
    duration_seconds: 233,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-002.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-002.webp`,
    shayari_quote: "Kuch yaadein be-awaaz hoti hain, bas aankhon se beh jaati hain.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "b23c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
    track_order: 3,
    title: "Saiyaara",
    artist: "Ek Tha Tiger / Saiyaara",
    duration_seconds: 371,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-003.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-003.webp`,
    shayari_quote: "Saiyaara tu toh sitaara bana, hum andheron mein bhatakte reh gaye.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "c34d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
    track_order: 4,
    title: "Sahiba",
    artist: "Stebin Ben, Jasleen Royal",
    duration_seconds: 191,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-004.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-004.webp`,
    shayari_quote: "Sahiba agar milna likha na tha, toh yeh faasle itne haseen kyun banaaye?",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "d45e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a",
    track_order: 5,
    title: "ISHQ (Slowed & Reverb)",
    artist: "Faheem Abdullah, Rauhan Malik",
    duration_seconds: 273,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-005.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-005.webp`,
    shayari_quote: "Ishq woh aag hai jismein khamoshi sabse zyada shor machati hai.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "e56f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b",
    track_order: 6,
    title: "Ishq Hai",
    artist: "Anurag Saikia",
    duration_seconds: 313,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-006.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-006.webp`,
    shayari_quote: "Tere bina har raat ek lambe intezaar jaisi lagti hai.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "f67a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c",
    track_order: 7,
    title: "Tum Hi Ho",
    artist: "Arijit Singh (Aashiqui 2)",
    duration_seconds: 262,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-007.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-007.webp`,
    shayari_quote: "Tere bina ab jee na sakenge, khud se hi rooth baithe hain hum.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "a78b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d",
    track_order: 8,
    title: "AGAR TUM SAATH HO",
    artist: "Alka Yagnik, Arijit Singh (Tamasha)",
    duration_seconds: 342,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-008.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-008.webp`,
    shayari_quote: "Pal bhar thehar jaao, yeh dard thoda aur sehne do.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "b89c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e",
    track_order: 9,
    title: "Tere Sang Yaara (Slowed + Reverb)",
    artist: "Atif Aslam",
    duration_seconds: 302,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-009.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-009.webp`,
    shayari_quote: "Woh lamhe jo tere saath the, wahi meri aakhiri panah hain.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "c90d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f",
    track_order: 10,
    title: "Sunn Raha Hai",
    artist: "Ankit Tiwari (Aashiqui 2)",
    duration_seconds: 391,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-010.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-010.webp`,
    shayari_quote: "Waqt ne cheen liya sab kuch, bas rone ka haq chhod diya.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "d01e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a",
    track_order: 11,
    title: "O Bedardeya (Film Version)",
    artist: "Arijit Singh, Pritam (TJMM)",
    duration_seconds: 326,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-011.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-011.webp`,
    shayari_quote: "Humne toh dil diya tha, tune toh saansein hi cheen leen.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "e12f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b",
    track_order: 12,
    title: "Chahun Main Ya Naa",
    artist: "Arijit Singh, Palak Muchhal (Aashiqui 2)",
    duration_seconds: 305,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-012.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-012.webp`,
    shayari_quote: "Tu bata de dil ki yeh uljhan, tujhe chahein ya khud ko bhula dein.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "f23a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c",
    track_order: 13,
    title: "Tum Hi Aana",
    artist: "Jubin Nautiyal (Marjaavaan)",
    duration_seconds: 250,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-013.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-013.webp`,
    shayari_quote: "Maut bhi aa jaaye toh ruk jaayegi, bas tera aana zaroori hai.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "a34b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d",
    track_order: 14,
    title: "Bulleya",
    artist: "Papon (Sultan)",
    duration_seconds: 186,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-014.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-014.webp`,
    shayari_quote: "Ranjhan de yaar bulleya, sun le meri fariyaad.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "b45c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e",
    track_order: 15,
    title: "Mere Rashke Qamar",
    artist: "Nusrat Fateh Ali Khan, Rahat Fateh Ali Khan",
    duration_seconds: 221,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-015.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-015.webp`,
    shayari_quote: "Aankh jhuki toh qayamat huyi, aankh uthi toh fasana ban gaya.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "c56d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f",
    track_order: 16,
    title: "Zihaal e Miskin",
    artist: "Vishal Mishra, Shreya Ghoshal",
    duration_seconds: 264,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-016.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-016.webp`,
    shayari_quote: "Zihaal-e-miskin makun baranjish, be-haal dil ki khabar lo.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "d67e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a",
    track_order: 17,
    title: "Lut Gaye",
    artist: "Jubin Nautiyal",
    duration_seconds: 229,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-017.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-017.webp`,
    shayari_quote: "Ek pal mein sab lut gaya, jab se tune nazar pheri.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "e78f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b",
    track_order: 18,
    title: "KABHI JO BAADAL BARSE",
    artist: "Arijit Singh (Jackpot)",
    duration_seconds: 255,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-018.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-018.webp`,
    shayari_quote: "Baarish ki har boond mein teri hi aahat mehsoos hoti hai.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "f89a0b1c-2d3e-4f5a-6b7c-8d9e0f1a2b3c",
    track_order: 19,
    title: "Zaroori Tha",
    artist: "Rahat Fateh Ali Khan",
    duration_seconds: 343,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-019.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-019.webp`,
    shayari_quote: "Lafz kam pad gaye the us din, warna dard behisaab tha.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "a90b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d",
    track_order: 20,
    title: "Teri Deewani",
    artist: "Kailash Kher",
    duration_seconds: 324,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-020.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-020.webp`,
    shayari_quote: "Ishq mein hum fanaa ho gaye, par tere deedar ko taras gaye.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "b01c2d3e-4f5a-6b7c-8d9e-0f1a2b3c4d5e",
    track_order: 21,
    title: "Bekhayali",
    artist: "Sachet Tandon (Kabir Singh)",
    duration_seconds: 372,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-021.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-021.webp`,
    shayari_quote: "Bekhayali mein bhi tera hi khayal aaye, aisi aadat bana di tune.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "c12d3e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f",
    track_order: 22,
    title: "Hamari Adhuri Kahani (Title Track)",
    artist: "Arijit Singh",
    duration_seconds: 399,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-022.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-022.webp`,
    shayari_quote: "Kahaani adhoori reh gayi, par zakham poore mil gaye.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "d23e4f5a-6b7c-8d9e-0f1a-2b3c4d5e6f7a",
    track_order: 23,
    title: "Phir Bhi Tumko Chaahunga",
    artist: "Arijit Singh, Shashaa Tirupati",
    duration_seconds: 352,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-023.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-023.webp`,
    shayari_quote: "Marte dam tak yeh dil tera hi naam pukarega.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "e34f5a6b-7c8d-9e0f-1a2b-3c4d5e6f7a8b",
    track_order: 24,
    title: "Roke Na Ruke Naina",
    artist: "Arijit Singh (Badrinath Ki Dulhania)",
    duration_seconds: 279,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-024.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-024.webp`,
    shayari_quote: "Koshish toh bohot ki rokne ki, par yeh naina baaghi nikle.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "f45a6b7c-8d9e-0f1a-2b3c-4d5e6f7a8b9c",
    track_order: 25,
    title: "Hasi (Male Version)",
    artist: "Ami Mishra (Hamari Adhuri Kahani)",
    duration_seconds: 273,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-025.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-025.webp`,
    shayari_quote: "Kabhi kisi ki hasi ban kar jeene ka maza hi kuch aur tha.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "a56b7c8d-9e0f-1a2b-3c4d-5e6f7a8b9c0d",
    track_order: 26,
    title: "Jhol (Slowed + Reverb)",
    artist: "Maanu x Annural Khalid (Coke Studio PK)",
    duration_seconds: 286,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-026.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-026.webp`,
    shayari_quote: "Dil ke jhol mein phans kar, hum khud ko hi haar baithe.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "b67c8d9e-0f1a-2b3c-4d5e-6f7a8b9c0d1e",
    track_order: 27,
    title: "Pal Pal",
    artist: "Afusic / Ali Zafar",
    duration_seconds: 147,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-027.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-027.webp`,
    shayari_quote: "Pal pal guzar raha hai, bas ek tera saya peeche chhoot raha hai.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "c78d9e0f-1a2b-3c4d-5e6f-7a8b9c0d1e2f",
    track_order: 28,
    title: "Afsos",
    artist: "PropheC",
    duration_seconds: 192,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-028.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-028.webp`,
    shayari_quote: "Afsos yeh nahi ki tum chali gayi, afsos yeh hai ki hum sambhal na sake.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "d89e0f1a-2b3c-4d5e-6f7a-8b9c0d1e2f3a",
    track_order: 29,
    title: "Taare",
    artist: "Tanishk Bagchi",
    duration_seconds: 155,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-029.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-029.webp`,
    shayari_quote: "Tootte taare ko dekh kar manga tha tujhe, shayad dua hi tooti huyi thi.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "e90f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b",
    track_order: 30,
    title: "Ae Dil Hai Mushkil Title Track",
    artist: "Arijit Singh, Pritam",
    duration_seconds: 270,
    audio_url: `${STORAGE_BASE_URL}/tracks/track-030.mp3`,
    cover_url: `${STORAGE_BASE_URL}/covers/cover-030.webp`,
    shayari_quote: "Junoon hai mera banu main tere kabil, tere bina guzara ae dil hai mushkil.",
    created_at: "2026-09-01T00:00:00.000Z",
  },
];

/**
 * Functional alias matching documentation contracts.
 */
export const PLAYLIST: Song[] = FALLBACK_TRACKS;
